version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: cargo
    directory: "/c-ares-sys/"
    schedule:
      interval: "weekly"
